---
name: Release Drafter Action

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  release-draft:
    uses: metal-stack/.github/.github/workflows/release-drafter.yaml@main
    secrets:
        token: ${{ secrets.GITHUB_TOKEN }}
